menu_items:
  - location: application
    label:
      en: AI Agent
      zh: AI 智能体
    url: "apps/ai-agent?theme={system_theme}"
    url_type: iframe
    background: "#f9f9f9|#e8e8e8"
    capsule:
      visible: true
      top: 10
      right: 10
require_version:
 version: "> 1.1.66"
 reason:
     en: "Requires new API features"
     zh: "需要新的API功能"