services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: dootask-ai-postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./dev-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dootask-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - ./dev-data/redis:/data